<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2l27ejp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2l27ejp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2l27ejp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2l27ejp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2l27ejp\appDevDebugProjectContainer([
    'container.build_hash' => '2l27ejp',
    'container.build_id' => '133679f0',
    'container.build_time' => 1578294944,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2l27ejp');
